# Autostart necessary processes (like notifications daemons,status bars,etc.)
# Or execute your favorite apps at launch like this:

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# goodies
exec-once = sleep .5 ; swaync
exec-once = sleep .25 ; waybar
exec-once = sleep .5 ; hyprsunset -t 4500
exec-once = awww-daemon --no-cache & disown ; sleep .5 ; python ~/.scripts/wallpicker.py image

# services
exec-once = sleep 1 ; systemctl start --user hyprpolkitagent
#exec-once = systemctl start --user app-com.mitchellh.ghostty.service

# daemon
exec-once = nm-applet & blueman-applet
exec-once = wl-paste --watch cliphist store ; wl-clip-persist --clipboard regular
exec-once = hypridle
