# Autostart necessary processes (like notifications daemons,status bars,etc.)
# Or execute your favorite apps at launch like this:

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# goodies
exec-once = sleep .5 ; swaync
exec-once = sleep 1 ;waybar
exec-once = sleep .5 ; pidof ^awww-daemon || awww-daemon --no-cache
exec-once = sleep 1; awww img -a $(python ~/.scripts/pick.py image) -t fade ; ln -sf "$(cut -d "$(printf "\u00a")" -f 3 .cache/awww/eDP-1)" /tmp/current-wallpaper
exec-once = sleep .5 ; hyprsunset -t 4500

# services
exec-once = sleep 1 ; systemctl start --user hyprpolkitagent

# daemon
exec-once = nm-applet & blueman-applet
exec-once = wl-paste --watch cliphist store
exec-once = wl-clip-persist --clipboard regular
exec-once = hypridle
