hl.env("XCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "Sweet-cursors")
-- hl.env("HYPRCURSOR_THEME", "Sweet-cursors-hyprcursor")
-- hl.env("HYPRCURSOR_SIZE", "32")
hl.env("GDK_SCALE", "1.25")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
-- hl.env("GTK_THEME", "Adwaita:dark")
hl.env("GTK_THEME", "WhiteSur-Dark")
hl.env("QT_QPA_PLATFORM", "wayland")
-- hl.env("GDK_BACKEND", "wayland")
hl.env("SDL_VIDEODRIVER", "wayland")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- hl.env("LIBVA_DRIVER_NAME", "nvidia")
-- hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
-- hl.env("GBM_BACKEND", "nvidia-drm")

-- hl.env("ENABLE_VKBASALT", "1")
-- hl.env("AQ_DRM_DEVICES", "/dev/dri/card0:/dev/dri/card2:/dev/dri/card1")

hl.env("ELECTRON_OZONE_PLATFROM_HINT", " wayland")
-- hl.env("WLR_NO_HARDWARE_CURSORS", "1")
-- hl.env("XDG_MENU_PREFIX", "plasma-")
