general {
    before_sleep_cmd = pidof hyprlock || hyprlock
		$temperature = hyprctl hyprsunset temperature
    after_sleep_cmd = hyprctl dispatch dpms on ; brightnessctl -r ; hyprctl hyprsunset temperature "$(hyprctl hyprsunset temperature 2> /dev/null)"
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

listener {
    timeout = 60
    on-timeout = brightnessctl -s ; brightnessctl set 0%
    on-resume = brightnessctl -r
}

listener {
    timeout = 110
    on-timeout = brightnessctl set 0%
    on-resume = brightnessctl -r
}

listener {
    timeout = 115
    on-timeout = hyprctl dispatch dpms off ; pidof hyprlock || hyprlock
}

listener {
    timeout = 120
    on-timeout = systemctl suspend
}
