general {
		#lock_cmd =
    before_sleep_cmd = hdmi_disable ; pidof hyprlock || hyprlock ; hyprctl reload
    after_sleep_cmd = brightnessctl -r ; hyprctl reload ; hyprctl reload
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

listener {
    timeout = 60
    on-timeout = brightnessctl -s ; brightnessctl set 0%
    on-resume = brightnessctl -r
}

listener {
    timeout = 110
    on-timeout = brightnessctl set 0%
    on-resume = brightnessctl -r
}

listener {
    timeout = 120
    on-timeout = systemctl suspend
}
