general {
		#lock_cmd =
    before_sleep_cmd = hdmi_disable ; sleep .5 ; pidof hyprlock || hyprlock
		$temperature = hyprctl hyprsunset temperature
		$monitor_reset = hdmi_disable ; for i in 1 2 3 ; do sleep .1 ; hyprctl reload ; done
    after_sleep_cmd = sleep .1 ; brightnessctl -r ; $temperature "$(hyprctl hyprsunset temperature 2> /dev/null)" ; $monitor_reset
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

listener {
    timeout = 60
    on-timeout = brightnessctl -s ; brightnessctl set 0%
    on-resume = brightnessctl -r
}

listener {
    timeout = 110
    on-timeout = brightnessctl set 0%
    on-resume = brightnessctl -r
}

listener {
    timeout = 120
    on-timeout = systemctl suspend
}
