$userbg = ~/.icon

general {
	hide_cursor = false
	ignore_empty_input = true
	text_trim = true
	immediate_render = true
	fail_timeout = 1000
}

background {
	monitor =
	path = /tmp/wallpaper
}

image {
	monitor =
	path = $userbg
	size = 200
	rounding = -1
	border_size = 2
	border_color = rgba(255, 255, 255, 1)
	rotate = 0
	position = 0,0
	halign = center
	valign = center
}

input-field {
	monitor =
	size = 175, 40
	outline_thickness = 0
	dots_size = 0.33
	dots_spacing = 0.15
	dots_center = true
	dots_rounding = -1
	outer_color = rgba(0, 0, 0, 0)
	inner_color = rgba(255, 255, 255, 0.5)
	font_color = rgba(255, 255, 255, 1)
	fade_on_empty = false
	fade_timeout = 1
	placeholder_text = <i> Enter Password </i>
	hide_input = false
	rounding = -1
	check_color = rgba(255, 255, 0, 0.25)
	fail_text = <i> Authentication failure </i>
	fail_color = rgba(255, 0, 0, 0.25)
	capslock_color = -1
	swap_font_color = false
	position = 0,320
	halign = center
	valign = bottom
}

label {
	monitor =
	text = cmd[update:100] echo "<b> "$(date +'%A, %-d %B %Y')" </b>"
	color = rgb(255, 255, 255)
	font_size = 24
	font_family = Noto Sans 10

	position = 0, -300
	halign = center
	valign = top
}

label {
	monitor =
	text = cmd[update:100] echo "<b><big> $(sh ~/.scripts/clock-icons.sh)   $(date +'%I:%M %p') </big></b>" # AM/PM
	color = rgb(255, 255, 255)
	font_size = 94
	font_family = Noto Nerd Font 10

	position = 0, -100
	halign = center
	valign = top
}


label {
	monitor =
	text = $USER
	position = 0, -140
}
