plugin {
	hyprbars {
		bar_height = 25
		bar_text_size = 11
		bar_buttons_alignment = left
		hyprbars-button = rgba(00000000), 20, 󰅙, hyprctl dispatch killactive, rgba(ff435dbf)
		hyprbars-button = rgba(00000000), 20, 󰐗, hyprctl dispatch fullscreen 1, rgba(ba13cebf)
		bar_blur = true
		bar_color = rgba(333333B5)
		bar_text_font = NotoSans Nerd Font Propo
		bar_part_of_window = false
		bar_button_padding = 0
		bar_precedence_over_border = true
		inactive_button_color = rgba(00000000)
		on_double_click = hyprctl dispatch fullscreen 1
	}

	hyprexpo {
		columns = 3
		gap_size = 25
		bg_col = rgb(202124)
		workspace_method = center current
		skip_empty = true
		enable_gesture = false
	}

	csgo-vulkan-fix {
		fix_mouse = true
		vkfix-app = hollow_knight.exe, 1920, 1080
	}
}

exec-once = hyprpm reload -n ; hyprctl dismissnotify
bind = $mainMod, TAB, exec, hyprctl dispatch hyprexpo:expo toggle
gesture = 3, up, dispatcher, hyprexpo:expo, on
gesture = 3, down, dispatcher, hyprexpo:expo, off
